#!/bin/sh
# OpenBao bootstrap for the demo stack (one-shot container, restart: "no"; idempotent).
#   1. Transit engine + the seed-protection key the bridge uses (BAO_TRANSIT_KEY=impala-seeds):
#      it seals every custodial seed and the card program issuer key.
#   2. OpenBao as a local OIDC test IdP so the admin UI's "Continue with OpenBao" SSO button works
#      without a real Okta/Auth0 org (login: testuser / testpassword). Ported from
#      impala-bridge/docker-compose.yml; the generated client_id is handed to the bridge through
#      /bootstrap/sso-config.json (CONFIG_FILE), because it is minted here and cannot live in compose.yaml.
# LOCAL DEMO ONLY: dev mode is in-memory and the root token is well known.
set -eu
: "${UI_ORIGIN:=http://localhost:3000}"
: "${OPENBAO_PUBLIC_URL:=http://localhost:8200}"
i=0
until bao status >/dev/null 2>&1; do
  i=$((i + 1))
  if [ "$i" -ge 90 ]; then
    echo "openbao-init: openbao not reachable at ${BAO_ADDR:-unset}" >&2
    exit 1
  fi
  sleep 1
done

bao secrets enable transit >/dev/null 2>&1 || true
bao write -f transit/keys/impala-seeds >/dev/null
echo "openbao-init: transit key impala-seeds ready (type $(bao read -field=type transit/keys/impala-seeds))"
# Canary: a ciphertext sealed by THIS key, kept on the bootstrap volume. Dev-mode OpenBao forgets its keys on
# restart; a re-created key (same name) decrypts nothing the bridge stored. up.sh and scenario 01 try to decrypt
# the canary, so a stack whose seeds are silently orphaned is caught before the first payment, not by it.
if [ ! -s /bootstrap/transit-canary.txt ]; then
  bao write -field=ciphertext transit/encrypt/impala-seeds plaintext="$(printf 'impala-suite-canary' | base64)" > /bootstrap/transit-canary.txt
  echo "openbao-init: transit canary written"
elif bao write -field=plaintext transit/decrypt/impala-seeds ciphertext="$(cat /bootstrap/transit-canary.txt)" >/dev/null 2>&1; then
  echo "openbao-init: transit canary still decrypts (same key as before)"
else
  echo "openbao-init: WARNING transit key re-created — every seed the bridge sealed before is undecryptable; run scripts/reset.sh" >&2
fi

# ── OIDC test IdP ─────────────────────────────────────────────────────────
# The browser POSTs the PKCE code exchange to OpenBao's token endpoint from the UI origin.
bao write sys/config/cors enabled=true allowed_origins="$UI_ORIGIN" >/dev/null
bao auth enable userpass >/dev/null 2>&1 || true
bao write auth/userpass/users/testuser password="testpassword" >/dev/null
bao write identity/entity name="testuser" metadata=email="testuser@example.com" >/dev/null 2>&1 || true
ENTITY_ID=$(bao read -field=id identity/entity/name/testuser)
UP_ACCESSOR=$(bao read -field=accessor sys/auth/userpass)
bao write identity/entity-alias name="testuser" canonical_id="$ENTITY_ID" mount_accessor="$UP_ACCESSOR" >/dev/null 2>&1 || true
# Explicit assignment: only listed entities may authorize.
bao write identity/oidc/assignment/impala-admins entity_ids="$ENTITY_ID" >/dev/null
bao write identity/oidc/scope/email description="email claim" template='{"email": {{identity.entity.metadata.email}}}' >/dev/null
bao write identity/oidc/scope/profile description="profile claims" template='{"preferred_username": {{identity.entity.name}}}' >/dev/null
# Public PKCE client (no secret; S256 mandatory). client_id is GENERATED by OpenBao.
bao write identity/oidc/client/impala-admin-ui \
  redirect_uris="$UI_ORIGIN/sso-callback.html" \
  assignments="impala-admins" client_type="public" \
  id_token_ttl="30m" access_token_ttl="1h" >/dev/null
CLIENT_ID=$(bao read -field=client_id identity/oidc/client/impala-admin-ui)
# Provider: the issuer must be the BROWSER-reachable base; OpenBao derives the provider URL from it.
bao write identity/oidc/provider/openbao \
  issuer="$OPENBAO_PUBLIC_URL" \
  allowed_client_ids="$CLIENT_ID" \
  scopes_supported="email,profile" >/dev/null

# All values must be JSON strings (the bridge's CONFIG_FILE loader reads them with as_str).
cat > /bootstrap/sso-config.json <<EOF
{
  "sso_providers": "openbao",
  "openbao_issuer_url": "$OPENBAO_PUBLIC_URL/v1/identity/oidc/provider/openbao",
  "openbao_internal_issuer_url": "http://openbao:8200/v1/identity/oidc/provider/openbao",
  "openbao_client_id": "$CLIENT_ID",
  "openbao_token_kind": "id",
  "openbao_allow_http": "true"
}
EOF
chmod 644 /bootstrap/sso-config.json
echo "openbao-init: OIDC test IdP ready (client_id $CLIENT_ID, issuer $OPENBAO_PUBLIC_URL)"
