#!/usr/bin/env python3
"""
captest.py - Higher-level interface for CAPRunner operations.

Subcommands:
  inspect          Pretty-print CAP file structure
  test             Run a test script against a CAP file
  generate-script  Generate a template test script for ImpalaApplet
"""

import argparse
import os
import subprocess
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
VENDOR_DIR = os.path.join(SCRIPT_DIR, "vendor")
CAPRUNNER_DIR = os.path.join(VENDOR_DIR, "caprunner")
DEFAULT_CAP = os.path.join(SCRIPT_DIR, "..", "applet", "build", "ImpalaApplet.cap")

PACKAGE_AID = "01 02 03 04 05 06 07 08"
APPLET_AID = "01 02 03 04 05 06 07 08 01 02"

# ANSI colors
GREEN = "\033[92m"
RED = "\033[91m"
YELLOW = "\033[93m"
CYAN = "\033[96m"
BOLD = "\033[1m"
RESET = "\033[0m"


def color(text, code):
    """Apply ANSI color if stdout is a terminal."""
    if sys.stdout.isatty():
        return f"{code}{text}{RESET}"
    return text


def check_setup():
    """Verify that setup.sh has been run."""
    venv = os.path.join(SCRIPT_DIR, ".venv")
    if not os.path.isdir(venv):
        print(color("Error: Virtual environment not found. Run ./setup.sh first.", RED))
        sys.exit(1)
    if not os.path.isdir(CAPRUNNER_DIR):
        print(color("Error: CAPRunner not found. Run ./setup.sh first.", RED))
        sys.exit(1)


def cmd_inspect(args):
    """Pretty-print CAP file structure."""
    check_setup()
    cap_file = args.cap or DEFAULT_CAP

    if not os.path.isfile(cap_file):
        print(color(f"Error: CAP file not found: {cap_file}", RED))
        print("Build first with: cd ../applet && gradle buildJavacard")
        sys.exit(1)

    print(color(f"{'='*60}", CYAN))
    print(color(f" CAP File Inspection: {os.path.basename(cap_file)}", BOLD))
    print(color(f"{'='*60}", CYAN))
    print()

    readcap = os.path.join(CAPRUNNER_DIR, "readcap.py")
    result = subprocess.run(
        [sys.executable, readcap, cap_file],
        capture_output=True, text=True
    )

    if result.returncode != 0:
        print(color("Error running readcap.py:", RED))
        print(result.stderr)
        sys.exit(1)

    # Pretty-print with section headers
    sections = [
        "Header", "Directory", "Applet", "Import", "ConstantPool",
        "Class", "Method", "StaticField", "ReferenceLocation",
        "Export", "Descriptor", "Debug"
    ]

    output = result.stdout
    for line in output.splitlines():
        # Highlight section names
        highlighted = False
        for section in sections:
            if line.strip().startswith(section):
                print(color(f"--- {line.strip()} ---", YELLOW))
                highlighted = True
                break
        if not highlighted:
            print(f"  {line}")

    print()
    print(color(f"{'='*60}", CYAN))
    print(color(" Inspection complete.", GREEN))


def cmd_test(args):
    """Run a test script against the CAP file."""
    check_setup()

    if not os.path.isfile(args.script):
        print(color(f"Error: Test script not found: {args.script}", RED))
        sys.exit(1)

    jc_version = args.version or "3.0.1"

    print(color(f"{'='*60}", CYAN))
    print(color(f" Running: {os.path.basename(args.script)} (JC {jc_version})", BOLD))
    print(color(f"{'='*60}", CYAN))
    print()

    runcap = os.path.join(CAPRUNNER_DIR, "runcap.py")
    with open(args.script, "r") as f:
        result = subprocess.run(
            [sys.executable, runcap, jc_version],
            stdin=f, capture_output=True, text=True
        )

    print(result.stdout)

    if result.returncode == 0:
        print(color("PASSED", GREEN))
    else:
        if result.stderr:
            print(result.stderr)
        print(color("FAILED", RED))

    sys.exit(result.returncode)


def cmd_generate_script(args):
    """Generate a template test script for ImpalaApplet."""
    name = args.name or "test_custom"
    output_path = os.path.join(SCRIPT_DIR, "scripts", f"{name}.txt")

    if os.path.exists(output_path) and not args.force:
        print(color(f"Error: {output_path} already exists. Use --force to overwrite.", RED))
        sys.exit(1)

    template = f"""-- {name}.txt
-- Custom test script for ImpalaApplet
-- Generated by captest.py

load: ../applet/build/ImpalaApplet.cap
install: 0b {PACKAGE_AID} {APPLET_AID.split()[-2]} {APPLET_AID.split()[-1]} 00 00 00 : 00

-- Select the applet
==> 00 A4 04 00 0A {APPLET_AID}
<== 90 00

-- Add your APDU test commands below:
-- Format:
--   ==> CLA INS P1 P2 [Lc] [Data...]    (send APDU)
--   <== [Data...] SW1 SW2               (expected response)
--
-- Common ImpalaApplet commands:
--   NOP:             INS 0x02
--   Is Card Alive:   INS 0x2E
--   Get Version:     INS 0x64
--   Initialize:      INS 0x2C (with random seed data)
--   Verify PIN:      INS 0x18 (P2=0x81 master, P2=0x82 user)
--   Get EC PubKey:   INS 0x24

-- Example: NOP
==> 00 02 00 00 00
<== 90 00
"""

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w") as f:
        f.write(template)

    print(color(f"Generated test script: {output_path}", GREEN))
    print(f"Edit the file to add your APDU test commands.")


def main():
    parser = argparse.ArgumentParser(
        description="CAPRunner helper for ImpalaApplet development",
        formatter_class=argparse.RawDescriptionHelpFormatter
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    # inspect
    p_inspect = subparsers.add_parser("inspect", help="Pretty-print CAP file structure")
    p_inspect.add_argument("cap", nargs="?", default=None, help="Path to CAP file (default: ImpalaApplet.cap)")

    # test
    p_test = subparsers.add_parser("test", help="Run APDU test script")
    p_test.add_argument("script", help="Path to test script file")
    p_test.add_argument("--version", "-v", default=None, help="JavaCard version (default: 3.0.1)")

    # generate-script
    p_gen = subparsers.add_parser("generate-script", help="Generate a template test script")
    p_gen.add_argument("--name", "-n", default=None, help="Script name (default: test_custom)")
    p_gen.add_argument("--force", "-f", action="store_true", help="Overwrite existing file")

    args = parser.parse_args()

    commands = {
        "inspect": cmd_inspect,
        "test": cmd_test,
        "generate-script": cmd_generate_script,
    }

    commands[args.command](args)


if __name__ == "__main__":
    main()
