package com.impala.applet;

import javacard.framework.Util;
import javacard.security.RandomData;

import static com.impala.applet.Constants.ZERO;
import static com.impala.applet.Constants.INT32_LENGTH;

/**
 * Represents a 4-byte random nonce used for replay protection.
 * Generated by the card and validated when the server sends signed commands
 * (e.g., SET_CARD_DATA, UPDATE_MASTER_PIN). The high bits are masked to keep
 * the nonce value small and positive.
 */
public class CardNonce {
    public final byte[] bytes;

    /** Creates a new random nonce using the card's secure RNG. High bits masked to 3 bits. */
    public CardNonce(RandomData randomData) {
        bytes = new byte[INT32_LENGTH];
        randomData.generateData(bytes, ZERO, INT32_LENGTH);
        bytes[0] &= (byte) 0x7;
    }

    /** Wraps an existing byte array as a nonce (used for lookup/comparison). */
    public CardNonce(byte[] bytes) {
        this.bytes = bytes;
    }

    /** Compares two nonces for byte-level equality. */
    public boolean equals(CardNonce other) {
        if (other == null) {
            return false;
        }
        return Util.arrayCompare(bytes, ZERO, other.bytes, ZERO, INT32_LENGTH) == 0;
    }
}
