package com.payala.impala.demo.auth

import android.app.Activity
import android.os.Bundle

/**
 * Transparent activity that handles the `impala://github-callback` deep link.
 *
 * Declared in the manifest with `android:launchMode="singleTask"` and an
 * intent-filter for the `impala` scheme / `github-callback` host. When GitHub
 * redirects the browser after OAuth authorization, this activity extracts the
 * `code` query parameter and passes it to [GitHubAuthHelper.pendingCallback].
 *
 * Finishes immediately so the user returns to [LoginActivity].
 */
class GitHubRedirectActivity : Activity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        val uri = intent?.data
        val state = uri?.getQueryParameter("state")
        val expectedState = GitHubAuthHelper.pendingState

        // This activity is exported (BROWSABLE deep link), so any app can fire
        // the callback with an attacker-chosen code. Only accept a callback
        // that echoes the state generated by startSignIn (login-CSRF guard,
        // mirroring OktaRedirectActivity).
        if (state == null || expectedState == null || state != expectedState) {
            GitHubAuthHelper.pendingCallback?.invoke(
                GitHubSignInResult.Error("Invalid state parameter")
            )
        } else {
            val code = uri?.getQueryParameter("code")

            if (code != null) {
                GitHubAuthHelper.pendingCallback?.invoke(GitHubSignInResult.CodeReceived(code))
            } else {
                val error = uri?.getQueryParameter("error") ?: "No authorization code received"
                GitHubAuthHelper.pendingCallback?.invoke(GitHubSignInResult.Error(error))
            }
        }
        GitHubAuthHelper.pendingCallback = null
        GitHubAuthHelper.pendingState = null

        finish()
    }
}
